### ISSUE TITLE
odroid_u3: problem: iptables/1.8.7 Failed to initialize nft: Protocol not supported

### ISSUE THREAD

**Issue by gociii** [hexdump0815/imagebuilder#100]
Getting the above when running iptables on odroid. Any ideas please?

update-alternatives --set iptables /usr/sbin/iptables-legacy - seems to be a workaround, but believe it can be resolved better adding nft support

**Comment by hexdump0815** [comment]
@gociii - most probably that is possible - in case you find out the minimal set of kernel options required for that to work i might add those options to future kernels ...

**Comment by gociii** [comment]
Issue related to https://github.com/hexdump0815/imagebuilder/issues/131

This can now be closed as it is resolved.
