### ISSUE TITLE
is it possible to change the linux distro?

### ISSUE THREAD

**Issue by cdd100** [hexdump0815/imagebuilder#102]
Would it be possible to replace the debian rootfs with an arm64 fedora rootfs and keep the other partitions? Just interested.

**Comment by hexdump0815** [comment]
@cdd100 - you just need /boot /lib/modules and maybe some files or tweaks for your system from the imagebuilder/systems/yoursystem dir and it should work with any common rootfs i would say ... so if you are familiar with doing such things it should not be a bit problem

**Comment by cdd100** [comment]
Ok, I am going to try to install a fedora silverblue rootfs. Hopefully it works. If not, I will try fedora workstation.

**Comment by cdd100** [comment]
It just gives me a kernel panic saying "no working init system found".

**Comment by cdd100** [comment]
I have done some more experimenting and it seems that any tampering with the system files (such as /usr or even /home) I get a kernel panic about no working init found. Does it have to do with permissions?

**Comment by cdd100** [comment]
I was able to covert to bedrock linux although.

**Comment by hexdump0815** [comment]
@cdd100 - sorry, can't help with this due to no time and no real fedora experience - i remember silverblue was something with a readonly rootfs maybe, so that would be way more complex, better try with some more normal version ... good luck

**Comment by cdd100** [comment]
I am just gonna stick to bedrock linux as it works extremely well.
