### ISSUE TITLE
misc: Is there an irc channel for the project?

### ISSUE THREAD

**Issue by unixabg** [hexdump0815/imagebuilder#112]
Greetings,
I am curious if there is an irc channel for the project? If not, I could set one up at oftc and just want to confirm a channel name.
Thank you for the project and your consideration.

**Comment by hexdump0815** [comment]
@unixabg - there is none and i'm already struggling to keep up with all the irc channels i'm already following :) ... i prefer to keep it with the github issues for now in case someone has problems with or ideas for the images ... as your focus seems to be on chromebooks then maybe this one could come close: https://oftc.irclog.whitequark.org/linux-cros-arm/ - it is in general about running mainline linux on chromebooks, so also postmarketos, archlinux etc.

if you want to setup a channel for this project here specifically feel free to do so as long as you maintain it and if needed moderate it as i have not enough time for that right now

best wishes - hexdump

**Comment by unixabg** [comment]
@hexdump0815 - thank you for the reply. I will checkout the channel. On special channels and keeping up I understand. Hence I think I will try the suggested for now. Marking issue closed.
