### ISSUE TITLE
misc: Missing License.

### ISSUE THREAD

**Issue by Demon-Gyoza** [hexdump0815/imagebuilder#132]
I Noticed the lack of a license for this... I would suggest licensing this under the GPL or Apache license.

**Comment by hexdump0815** [comment]
you are right - its maybe time to add a proper license to it - i'll add a gpl one soon

**Comment by hexdump0815** [comment]
added: https://github.com/hexdump0815/imagebuilder/commit/00386bf166c0291de01fbcf5863c6cf183f51c99

**Comment by Demon-Gyoza** [comment]
Wait... Do I get to be a contributor because I contributed to this by suggesting to add a license?

**Comment by hexdump0815** [comment]
i would count this as a suggestion, but not as a real contribution - but in the end its up to you how you see it

**Comment by Demon-Gyoza** [comment]
Okay, I guess... I'm relatively new to Github and am lacking general knowledge about how the site operates.
