### ISSUE TITLE
misc: btrfs property set (compression) imagebuilder-diskimage: Invalid argument

### ISSUE THREAD

**Issue by gociii** [hexdump0815/imagebuilder#139]
Hi all,

Getting the following error on this command....

/compile/local# btrfs property set /compile/local/imagebuilder-diskimage compression none
_ERROR: failed to set compression for /compile/local/imagebuilder-diskimage: Invalid argument_

Perhaps it is ok to ignore?  Is it because compression might not be supported at all?

**Comment by hexdump0815** [comment]
@gociii - i also saw it and did a quick check back then and i think it can be safely ignored - seems to be some incompatibility between kernel (newer) and btrfs tools (older) i think, iirc the default is correct, so even if it gives an error things should work just fine ...
