### ISSUE TITLE
chromebook_kukui: misc: Patch that fixed high pitch sound for kukui?

### ISSUE THREAD

**Issue by aneeshlingala** [hexdump0815/imagebuilder#151]
What is the patch that fixed the high pitch sound when turning on back from sleep for kukui? I would like to add it to the linux-aarch64 kernel for Arch Linux ARM just like your bluetooth patch.

**Comment by hexdump0815** [comment]
i'm not aware of any specific patch for this problem, i guess just the newer kernel fixed it by changes in the audio subsystem in the newer kernels maybe - so hopefully it should just work on your arch kernel as well as long as it is at least v6.1.11 or newer

**Comment by aneeshlingala** [comment]
The linux-aarch64 kernel is 6.2, but the problem is still not gone. Not that big of an issue. Closing
