### ISSUE TITLE
Mounting system volume (Not the one on the SDCard

### ISSUE THREAD

**Issue by Dae-Hang-Sook** [hexdump0815/imagebuilder#165]
When trying to open up the 54GB volume for the chromebook it twll be it can't mount it. "Error mounting /dev/mmcblk0p1 at /media/linux/d598f39d-a855-4751-ab92-3b84db0d00c5: wrong fs type, bad option, bad superblock on /dev/mmcblk0p1, missing codename or helper program, or other error" Any thoughts?
My original plan was to copy and write this already created system onto my chromebook after wiping its main drive.
Device - Kukui

**Comment by hexdump0815** [comment]
for moving your installation to emmc on a chromebook please have a look at: https://github.com/hexdump0815/imagebuilder/blob/main/doc/install-to-emmc-on-arm-chromebooks.md
