### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by Dae-Hang-Sook** [hexdump0815/imagebuilder#168]
Is it safe to apply updates now? Last time when I applied any type of update it caused to device to be unbootable.

**Comment by hexdump0815** [comment]
updating (i.e. /scripts/update-system.sh) should be safe usually - just make sure you extended the rootfs beforehand - otherwise the disk might run full

**Comment by Dae-Hang-Sook** [comment]
> updating (i.e. /scripts/update-system.sh) should be safe usually - just make sure you extended the rootfs beforehand - otherwise the disk might run full

Will do, thanks.
