### ISSUE TITLE
incorrect file name referenced by script 

### ISSUE THREAD

**Issue by N4IRS** [hexdump0815/imagebuilder#19]
In systems/chromebook_oak/get-files.sh on line 8:
( cd ${DOWNLOAD_DIR} ; tar xzf kernel-chromebook_oak-aarch64.tar.gz boot ; mv boot/vmlinux.kpart-oak-* boot-chromebook_oak-aarch64.dd ; rm -rf boot )

The mv is pointing at boot/vmlinux.kpart-oak-* The actual file name is vmlinux.kpart-elm* in 5.10.25-stb-mt7+.tar.gz

**Comment by hexdump0815** [comment]
good catch - thanks for this info -  i'll build the next mt7 kernel with the proper oak name (https://github.com/hexdump0815/linux-mainline-mediatek-mt81xx-kernel/commit/4f6ed3ee17551b502ddf38706b68f0330db11fa9) - for the meantime i have added the intermediate names as a hack (https://github.com/hexdump0815/imagebuilder/commit/7b87f1a98cf32ec3e1bd04b09628b048c7119dfb)
