### ISSUE TITLE
Missing indented if in create-image.fs?

### ISSUE THREAD

**Issue by baybled** [hexdump0815/imagebuilder#190]
Error on line 402 ( *[ "$3" = "bookworm" ]; then* ) 

missing an indented "if" as per line 382  ( *if [ "$3" = "bookworm" ]; then* ). 

[link to file in question](https://github.com/hexdump0815/imagebuilder/blob/main/scripts/create-image.sh)

now i know how the linters feel

**Comment by hexdump0815** [comment]
@baybled - oh thanks a lot for reporting this - it looks that was a mistake i seem to have introduced during the bulleye and focal support removal in https://github.com/hexdump0815/imagebuilder/commit/e20a5dfbfa7105932941ec26bf7ff0e1cfcd8174 ... i'll fix it immediately

**Comment by hexdump0815** [comment]
fixed with https://github.com/hexdump0815/imagebuilder/commit/673537b9682e3c43ada64d37cd68234b0c6a7269
