### ISSUE TITLE
Display static and no boot on sku0 [Kukui Chromebook Duet]

### ISSUE THREAD

**Issue by ClockworkElijah54** [hexdump0815/imagebuilder#20]
Hello, I tried to boot focal on my Chromebook Duet and the display never turned on besides some static. The reason I mentioned sku0 is because of the Cadmium discord, which instructed me to run a command that revealed a difference in display panels, the cause of the issue. It was resolved using a kernel patch.

**Comment by hexdump0815** [comment]
hi, i have read it in the cadmium context. the kernel used here does not have the sku0 dtb in yet. i can try to add it and prepare you a new kernel tar.gz in a few days. do you have another machine at hand which you can use to add such a new kernel to the written image?

best wishes - hexdump

**Comment by ClockworkElijah54** [comment]
Yes, I do. Thank you for asking, and message me back when you get it ready :)

**Comment by ClockworkElijah54** [comment]
Hello, I'm just curious if you've made any progress on this issue? Thank you

**Comment by hexdump0815** [comment]
i'll not get to it before the weekend - i'll ping you here when i have something ready - so stay tuned

**Comment by ClockworkElijah54** [comment]
Ah ok, thank you

**Comment by hexdump0815** [comment]
what does "cat /proc/device-tree/model" say exactly in chromeos for your duet - "MediaTek krane rev3/rev4 sku0 board" or "MediaTek krane sku0 board"?

**Comment by ClockworkElijah54** [comment]
In crosh or root shell? I tried crosh and it said "Unknown command: cat"

**Comment by hexdump0815** [comment]
in the root shell

**Comment by hexdump0815** [comment]
can you please give this one a try? - https://github.com/hexdump0815/linux-mainline-mediatek-mt81xx-kernel/releases/download/5.13.2-stb-mt8%2B/5.13.2-stb-mt8+.tar.gz

just do the following (assuming sdcard to be your sdcard device with the kukui image on it) on some linux machine:
```
mount /dev/sdcardp4 /mnt
mount /dev/sdcardp3 /mnt/boot
cd /mnt
tar xzf  5.13.2-stb-mt8+.tar.gz
dd if=boot/vmlinux,kpart-5.13.2-stb-mt8+ of=/dev/sdcardp1
umount /mnt/boot /mnt
```
and then boot your duet with it and let me know if it will work

good luck and best wishes - hexdump

**Comment by ClockworkElijah54** [comment]
Ah ok, thank you :D I missed your last message, sorry

**Comment by ClockworkElijah54** [comment]
It worked, it booted fine with no issue, but the screen rotation is still wrong, just so you know

**Comment by hexdump0815** [comment]
on krane screen rotation of xorg is corrected on first boot, so should be correct on second one, but maybe your model string in the dtb is so different that the script does not catch it :)

**Comment by ClockworkElijah54** [comment]
Ah ok, no problem, can you close this or is there more to this that needs testing?

**Comment by hexdump0815** [comment]
if it works for you now i think we can close it ... btw. just updated the images and they now contain that kernel with more dtb files by default :)

best wishes and thanks for testing - hexdump

**Comment by ClockworkElijah54** [comment]
Cool, thanks
