### ISSUE TITLE
Disable command line boot

### ISSUE THREAD

**Issue by gufuskn** [hexdump0815/imagebuilder#200]
How do I disable command line boot?
I'm on the Lenovo IdeaPad Flex 3 mt8183 Chromebook

**Comment by hexdump0815** [comment]
i do not really understand what you want - can you please try to explain it once more in other and maybe a few more words?

**Comment by gufuskn** [comment]
When the Chromebook turns on, there are 8 penguins at the top and processes that say “OK” and “FAILED”

**Comment by gufuskn** [comment]
![image](https://github.com/hexdump0815/imagebuilder/assets/159094252/74bf3bc8-e2f6-46a1-a5ca-f52e9c6d93e9)

**Comment by unixabg** [comment]
@gufuskn - you might try adding the boot param quiet . And you could consider adding the package plymouth

**Comment by hexdump0815** [comment]
have a look at https://github.com/hexdump0815/imagebuilder/issues/194 maybe

**Comment by gufuskn** [comment]
> have a look at #194 maybe

Alright, thanks
