### ISSUE TITLE
Can't boot into debian or Ubuntu aarch64 image, beeps when I press Ctrl+U

### ISSUE THREAD

**Issue by jonathan011Hh** [hexdump0815/imagebuilder#221]
Can't boot into debian or Ubuntu aarch64 image, beeps when I press Ctrl+U, (I followed all the instructions and I made sure my device was supported I'm currently using a Lenovo IdeaPad 3 mt8183 chromebook
architecture is "aarch64" 
thx for ur time all help  is appreciated

**Comment by LukIsHere** [comment]
hi
u actually need to enable developer mode and booting from usb for this to work

Turn off the chromebook, then press and hold volume up, volume down, and power simultaneously until menu pops up (around 10 or so seconds).
In there enable developer mode.

After that go back to chromeos, it should be reseted, don't set it up again. Press ctrl+alt+Refresh, login as chronos (no password).
Type ```sudo crossystem dev_boot_usb=1 dev_boot_signed_only=0```
You can also set gbb flags there, look [here](https://wiki.postmarketos.org/wiki/Category:ChromeOS#Installation)

After rebooting you should be able to boot from external device using menu.
Also more details on process i described should be [here](https://wiki.postmarketos.org/wiki/Category:ChromeOS#Installation)

**Comment by LukIsHere** [comment]
also isn't ideapad duet 3 	Qualcomm Snapdragon 7c?
https://wiki.postmarketos.org/wiki/Lenovo_IdeaPad_Duet_3_(google-wormdingler)

**Comment by jonathan011Hh** [comment]
hey, I did all of those things it just, beeps after hang of  black screen and beeps lol don't know what to do my device is in dev mode and also supported:(

**Comment by jonathan011Hh** [comment]
not yet, I'll try that, :/

**Comment by LukIsHere** [comment]
ok lemme know if it works👍

**Comment by jonathan011Hh** [comment]
one question were is exactly the "7c" image I cant seem to find it?

**Comment by LukIsHere** [comment]
'll tell u just quick question
is this your device https://pcsupport.lenovo.com/us/en/products/chromebook-laptops/lenovo-chromebooks-series/ideapad-3-chrome-14m836/documentation/doc_userguide
or this one https://pcsupport.lenovo.com/us/pl/products/chromebook-laptops/lenovo-chromebooks-series/duet-3-chrome-11q727/document-userguide/doc_userguide ?

**Comment by jonathan011Hh** [comment]
I found it its downloading, how do I boot from it I pressed Ctrl+U it beeps(earlier) so hopefully when I do this it'll boot properly if not I might have to go a different route I'll post updates.

**Comment by LukIsHere** [comment]
if the first one the 7c image won't work
just send a video if u can
and also tell me how you flashed the usb or sd card?
it usually does the beep if it doesn't detect a device to boot from

**Comment by jonathan011Hh** [comment]
oh ok, also my device is the top link u sent me, asking which device I have(Lenovo IdeaPad 3 Chromebook)
updates coming soon

**Comment by jonathan011Hh** [comment]
it did not work im unable to send a video rn, is there anything else i can do its at dev screen i press keys to boot and it goes black and then back to the screen and beeps very loudy lol idkw to do:<

**Comment by jonathan011Hh** [comment]
> if the first one the 7c image won't work just send a video if u can and also tell me how you flashed the usb or sd card? it usually does the beep if it doesn't detect a device to boot from

well I did enable dev USB booting etc, and I booted using control+U keys.

**Comment by LukIsHere** [comment]
also are you sure you have arm variant? there is also x64 variant
https://pcsupport.lenovo.com/us/en/products/chromebook-laptops/lenovo-chromebooks-series/ideapad-3-cb-14igl05/documentation/doc_userguide

**Comment by jonathan011Hh** [comment]
"14M836" hopefully that's the M.O.

**Comment by jonathan011Hh** [comment]
model number*

**Comment by jonathan011Hh** [comment]
yes I don't have Intel or AMD or armv9l or anything like that its a (CPU) "mediatek Kamponio 500 mt8183"
architecture "Aarch64"

**Comment by LukIsHere** [comment]
ok i checked it is an arm one
https://psref.lenovo.com/syspool/Sys/PDF/IdeaPad/IdeaPad_3_CB_14M836/IdeaPad_3_CB_14M836_Spec.pdf
will have a look into hardware maintenance manual for more info gimme a moment

**Comment by jonathan011Hh** [comment]
ok

**Comment by LukIsHere** [comment]
did you use usb or micro sd card?
how did you flash it?

**Comment by jonathan011Hh** [comment]
i used usb, and i put the file u told me to download into the usb slot and then i rebooted and pressed ctrl+U

**Comment by jonathan011Hh** [comment]
I did use it I just enabled it again to make sure

**Comment by LukIsHere** [comment]
have you flashed the file or just put it onto the usb?

**Comment by jonathan011Hh** [comment]
just put it into the USB.

**Comment by LukIsHere** [comment]
bruh

**Comment by jonathan011Hh** [comment]
oh how do I flash it(srry)

**Comment by LukIsHere** [comment]
you need to flash the file
what system do u have on your main pc?

**Comment by jonathan011Hh** [comment]
Mac and windows

**Comment by jonathan011Hh** [comment]
like using belena etcher? and then boot it onto chromebook

**Comment by jonathan011Hh** [comment]
*for example(belenaetcher)*

**Comment by LukIsHere** [comment]
on on windows use this https://sourceforge.net/projects/win32diskimager/
select the mt8183 image
select your usb
click write

**Comment by LukIsHere** [comment]
after that just plug it in and it should boot

**Comment by jonathan011Hh** [comment]
ok I'll give it a shot, let u know if its succesfull

**Comment by jonathan011Hh** [comment]
can I use etcher tho? my windows takes for ever to boot up (I have windows 11 loaded on MacBook pro).

**Comment by LukIsHere** [comment]
balena etcher works too

**Comment by jonathan011Hh** [comment]
thx giving it a shot.

**Comment by jonathan011Hh** [comment]
I tried it it still beeps

**Comment by jonathan011Hh** [comment]
doesn't boot whatsoever

**Comment by LukIsHere** [comment]
i forgot the image is compressed
try unpacking it with some archive program so it's .img and then flashing

**Comment by jonathan011Hh** [comment]
oh ok did that testing it now

**Comment by jonathan011Hh** [comment]
it dosnt work still😔

**Comment by jonathan011Hh** [comment]
my USB and USB port r fine it just doesn't want to boot lol

**Comment by LukIsHere** [comment]
weird
you know mac os had dd so you can try using that

on ur mac
first ```diskutil list``` fin ur usb
then ```dd of=image.img if=/dev/yourUSB status=progress```

**Comment by jonathan011Hh** [comment]
oh well I cant install it on my chromebook

**Comment by jonathan011Hh** [comment]
?

**Comment by LukIsHere** [comment]
you can kinda install it directly but it is very risky

**Comment by jonathan011Hh** [comment]
no I mean just boot it off of a USB, also is there a way to get legacy on Aarch64 architecture

**Comment by LukIsHere** [comment]
not sure what you mean by legacy boot

**Comment by jonathan011Hh** [comment]
nvm I mean like is there a way to boot from USB on a arm Chromebook idkw but it still isn't working:/

**Comment by LukIsHere** [comment]
try setting the gbb flags if u haven't it might help make sure you have usb boot enabled

**Comment by LukIsHere** [comment]
read the gbb flags section
https://wiki.postmarketos.org/wiki/Category:ChromeOS

**Comment by jonathan011Hh** [comment]
I cant disable write protection it says "failed to apply new settings: unknown WP error"

**Comment by LukIsHere** [comment]
yeah don't worry about that just ```futility gbb --set --flash --flags=0x19``` it should work anyway

**Comment by jonathan011Hh** [comment]
oh I got error=  that I have to disable WP(write-protection)

**Comment by LukIsHere** [comment]
weird your device shouldn't have hardware one
could you pls try running
```sudo crossystem dev_boot_usb=1 dev_boot_signed_only=0```
again and see if it solves the problem
if it doesn't it's probably usb flashed incorrectly

**Comment by jonathan011Hh** [comment]
I already did lol like 6 times it doesn't like it and I did use UNETBOOTIN to write to USB if that changes anything

**Comment by LukIsHere** [comment]
it should be one of this images https://github.com/hexdump0815/imagebuilder/blob/main/systems/chromebook_kukui/readme.md
your probably want exactly this one https://github.com/hexdump0815/imagebuilder/releases/tag/230917-01
**uncompressed** with balena etcher

**Comment by jonathan011Hh** [comment]
ok Im trying different file and I already tried thos

**Comment by jonathan011Hh** [comment]
ok trieing it lets c ifdis works

**Comment by jonathan011Hh** [comment]
it still beeps:<  😭

**Comment by LukIsHere** [comment]
damn 'm out of ideas
can you try with micro sd card?
provide a recording?

**Comment by jonathan011Hh** [comment]
yes will do so

**Comment by jonathan011Hh** [comment]
I cant record and don't have a sd card--well lmk real quick!

**Comment by LukIsHere** [comment]
sorry i don't really know how to help u more on that one then
maybe someone else does but u will have to wait some time for that

**Comment by jonathan011Hh** [comment]
oh ok:< thx for helping me out I will close this issue.
