### ISSUE TITLE
Sound and mic not working on Kappa (Ubuntu Focal SD Card Image)

### ISSUE THREAD

**Issue by aneeshlingala** [hexdump0815/imagebuilder#50]
Sound is not working on kappa, I have alsa installed. It shows dummy output for sound and the mic. Please fix it fast.

I think i found the changes in the mainline linux kernel that add sound support for mt8183: https://github.com/torvalds/linux/tree/master/sound/soc/mediatek/mt8183 Would this be of any help?

**Comment by hexdump0815** [comment]
@aneeshlingala - i have sound working on my kappa, so in principle it works ... as the linux kernel v5.18.0 and mesa v22.1.0 i'm right now in the process of building new kernels and images and most probably it will work with those then - so please wait a few more days and then the chances are good that it will work ... but the sound from the built in mic will be very low and the mic connector does not work yet, so if you rely on a working mic, better get a cheap usb audio dongle for now ...

**Comment by aneeshlingala** [comment]
Oh, thanks!

**Comment by aneeshlingala** [comment]
Ok thanks!

**Comment by aneeshlingala** [comment]
When can we expect the release? It has been a few days now...

**Comment by hexdump0815** [comment]
sorry - this is a spare time project, so it will move on whenever i have time - "a few days" might be within the next week or within the next weeks depending on how well everything is working ...

**Comment by aneeshlingala** [comment]
Ok

**Comment by hexdump0815** [comment]
new kukui images are ready: https://github.com/hexdump0815/imagebuilder/releases/tag/220528-01

**Comment by aneeshlingala** [comment]
Thanks!
