### ISSUE TITLE
problem: chromebook_kukui: bluetooth no longer working in v5.18

### ISSUE THREAD

**Issue by hexdump0815** [hexdump0815/imagebuilder#55]
bluetooth was working well in v5.15 but seems to be broken in v5.18

**Comment by BenjaminWegener** [comment]
mazbe it has something to do with https://github.com/hexdump0815/imagebuilder/tree/main/systems/chromebook_kukui/extra-files/lib/firmware/qca ?

**Comment by aneeshlingala** [comment]
Sadly, this is broken for all kukui devices.

**Comment by aneeshlingala** [comment]
Also on kappa, Blueman doesn't detect any adapter, must be a kernel module or related issue.

**Comment by hexdump0815** [comment]
it is not related to the firmware i guess as it is working fine with up to v5.17 ... as v5.17 is working and v5.18 is broken it should be possilbe to git bisect this problem between those to kernel versions - just a matter of effort :) ... maybe i'll give it a try over the weekend

**Comment by aneeshlingala** [comment]
sure

**Comment by aneeshlingala** [comment]
is there newer bluetooth firmware from 5.17 for bluetooth? If so, try using that firmware in the 5.18 kernel, this issue might be related to this: https://www.spinics.net/lists/stable/msg491263.html

**Comment by hexdump0815** [comment]
that would be https://github.com/gregkh/linux/commit/0ea9fd001a14ebc294f112b0361a4e601551d508 and it looks like it was fixed shortly after with https://github.com/gregkh/linux/commit/0ea53674d07fb6db2dd7a7ec2fdc85a12eb246c2 ... so i guess this was a different problem

**Comment by aneeshlingala** [comment]
If you post the updated image, can we update from a older version?

**Comment by hexdump0815** [comment]
@aneeshlingala - there is currently no automated way to update the kernel - best is to just compile a new one or untar a newer build if one is available and install it

**Comment by hexdump0815** [comment]
problem kind of solved: drivers/tty/serial/8250/8250_mtk.c needs to be reverted to the v5.17 state to make bluetooth work for kukui devices on v5.18 ... i'll add a proper patch to the repo and build a new kernel during the next days

**Comment by aneeshlingala** [comment]
I think you can use dd to get two images from the two kernel partitions while booting in the live USB/SD card and flash those two images to the kernel partitons on eMMC and chroo into the eMMC install and run` sudo update-initramfs -u`

**Comment by BenjaminWegener** [comment]
do we know which of the [patches](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/drivers/tty/serial/8250/8250_mtk.c?h=v5.18.1) is responsible?

**Comment by hexdump0815** [comment]
i have added the patch now: https://github.com/hexdump0815/linux-mainline-mediatek-mt81xx-kernel/blob/master/misc.cbm/patches/5.18.0/mt8183-fix-bluetooth.patch ... i think it were 3 commits for the mtk serial driver - maybe some refactoring which broke things in the end - you can see the commits via a git log of the patched file

**Comment by BenjaminWegener** [comment]
@hexdump0815 thank you very much! can confirm, its working now using your patch from the repo

**Comment by hexdump0815** [comment]
new images with fixed bluetooth are out, so lets close this issue ...
