### ISSUE TITLE
chromebook_kukui: problem: acer cp311-3h boot

### ISSUE THREAD

**Issue by crazycusti** [hexdump0815/imagebuilder#59]
hello, i have a question about the boot process. this is a little bit offtopic.

i copy the newest image on my mmc storage, works perfect.

while im powering on, the "developer mode" hint appears and 2 very loud beeps. any way to turn it off and boot directly to the mmc flash? the beep is very annonying.

and i heard about, when the battery is completely drained, the developer mode will reset and the "secure boot" is active. that.. is not so good. is that true? can i fix them?

many thanks for any help!

**Comment by hexdump0815** [comment]
@crazycusti - hopefully carefully reading through https://github.com/hexdump0815/linux-mainline-on-arm-chromebooks should answer most of your questions - if not, please let me know

best wishes - hexdump
