### ISSUE TITLE
misc: Dualbooting?

### ISSUE THREAD

**Issue by cdd100** [hexdump0815/imagebuilder#95]
I have a lenovo C330 with a 64gb EMMC. Is it possible to dualboot chrome os and ubuntu on the emmc and get a selection menu on boot? Thanks.

**Comment by aneeshlingala** [comment]
@cdd100 You can do this by flashing Ubuntu (not chromeos) onto a SD Card or usb (SD Card preferred), but you won't get a selection menu, instead you have to press CTRL U to boot into Ubuntu, or press CTRL D to boot into chromeos, but make sure that you need to have developer mode enabled.

**Comment by cdd100** [comment]
I have ubuntu on a usb already and it works fine, I was wondering if I could dualboot on to the emmc and not need to carry a usb with me, since I need to keep chrome os.

**Comment by hexdump0815** [comment]
i think to have both on emmc will not work as chromeos is not allowing something like this as far as i know ...

**Comment by cdd100** [comment]
Ok, thanks!

**Comment by aneeshlingala** [comment]
I'd recommend a sd card, since it is hard to notice without trying to find it, and also don't try to format it from ChromeOS, or it will not work anymore.
