### ISSUE TITLE
Custom bootscreen?

### ISSUE THREAD

**Issue by cdd100** [hexdump0815/imagebuilder#99]
Wondering if I could get a custom bootscreen instead of a verbose boot?

**Comment by hexdump0815** [comment]
@cdd100 - it is possible by adding "quiet splash" to the kernel boot options - this would require to rebuild the kpart kernel boot image as it contains the kernel cmdline args ... i prefer to leave it verbose by default to easier see what goes wrong in case something goes wrong for someone ...

**Comment by cdd100** [comment]
Ok, I can settle with verbose.
